python og_train.py \
    --dataset_name /media/jj_data/data/CLIP \
    --dataset_config_name image_only \
    --image_column_name pixel_values \
    --output_dir /home/jackmorris/football/football2text/models/ViT/3 \
    --mask_ratio 0.50 \
    --norm_pix_loss \
    --do_train \
    --do_eval \
    --base_learning_rate 1.5e-4 \
    --lr_scheduler_type cosine \
    --weight_decay 0.05 \
    --num_train_epochs 10 \
    --warmup_ratio 0.05 \
    --per_device_train_batch_size 150 \
    --per_device_eval_batch_size 200 \
    --logging_strategy steps \
    --logging_steps 10 \
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --load_best_model_at_end True \
    --save_total_limit 3 \
    --seed 1337 \