python run_clip.py \
    --output_dir /media/jj_data/models/CLIP/1 \
    --model_name_or_path /media/jj_data/models/clip-roberta \
    --dataset_name /media/jj_data/data/CLIP \
    --dataset_config_name default \
    --image_column pixel_values \
    --caption_column input_ids \
    --remove_unused_columns True \
    --do_train \
    --do_eval \
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 64 \
    --learning_rate 5e-5 \
    --warmup_steps 0 \
    --weight_decay 0.1 \
    --overwrite_output_dir \
    --logging_strategy steps \
    --logging_steps 10 \
    --evaluation_strategy epoch